spring:
  application:
    name: appdistribuidas
  datasource:
    url: jdbc:postgresql://localhost:5434/facturacion
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    listener:
      simple:
        auto-startup: true
        acknowledge-mode: auto
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
